Implement GetUnitFlags(), GetUnitFlagsTwo(), SetUnitFlags(flags), Set… …UnitFlagsTwo(flags)
azerothcore/mod-eluna pull request #137
Opened 2023-05-16 02:34 UTC by New-HavenWotLK

Implemented the stated hooks to the source... tested them... they worked fine! =D

2023-05-17 00:04 UTC, New-HavenWotLK commented
@Helias if u got some time, could u check it out pls? =D

thx in advance! ^.^

2023-05-20 02:28 UTC, New-HavenWotLK commented
added also now 2 new hooks which i have tested as well =)

they worked fine when checking the hooks via a print statement =D

2023-05-20 09:11 UTC, Helias commented
thanks for your PR!
If the pipeline will pass successfully I will merge this PR

2023-05-20 09:41 UTC, Helias commented
error in the build
```
/home/runner/work/mod-eluna/mod-eluna/modules/mod-eluna/src/LuaEngine/PlayerHooks.cpp:694:13: fatal error: out-of-line definition of 'OnApplyAura' does not match any declaration in 'Eluna'
void Eluna::OnApplyAura(Player* player, Aura* aura, bool isNewAura)
            ^~~~~~~~~~~
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:328: modules/CMakeFiles/modules.dir/mod-eluna/src/LuaEngine/PlayerHooks.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1199: modules/CMakeFiles/modules.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

2023-05-20 13:21 UTC, r-o-b-o-t-o requested changes
Hi there, thanks for the PR!

Looks like some parts are missing for your hooks, see this commit for an example on how to add a hook: https://github.com/azerothcore/mod-eluna/commit/85714c1123489ff8d110f50a4701b293acc95c43

Also, could you document your additions in `README.md` please? See https://github.com/azerothcore/mod-eluna/commit/2a683a59e37cf08f4912aac2016467d99f412849 and the other commit I linked for examples.

2023-05-20 13:21 UTC, r-o-b-o-t-o commented on src/LuaEngine/CreatureMethods.h
> +    */
```suggestion
    /**
     * Returns the [Creature]'s Unit flags.
     *
     * These are used to control whether the NPC is attackable or not, among other things.
     *
     * @return [UnitFlags] unitFlags
     */
```

2023-05-20 13:21 UTC, r-o-b-o-t-o commented on src/LuaEngine/CreatureMethods.h
> +    */
```suggestion
    /**
     * Returns the [Creature]'s Unit flags 2.
     *
     * @return [UnitFlags2] unitFlags2
     */
```

2023-05-20 13:21 UTC, r-o-b-o-t-o commented on src/LuaEngine/CreatureMethods.h
> +
```suggestion
```

2023-05-20 13:21 UTC, r-o-b-o-t-o commented on src/LuaEngine/CreatureMethods.h
> +    */
```suggestion
    /**
     * Sets the [Creature]'s Unit flags to `flags`.
     *
     * @param [UnitFlags] flags
     */
```

2023-05-20 13:21 UTC, r-o-b-o-t-o commented on src/LuaEngine/CreatureMethods.h
> +    */
```suggestion
    /**
     * Sets the [Creature]'s Unit flags2 to `flags`.
     *
     * @param [UnitFlags2] flags
     */
```

2023-05-20 15:23 UTC, New-HavenWotLK commented
ah uups... XD

i will look to fix this when i am home tomorrow =)

2023-05-20 17:17 UTC, New-HavenWotLK commented
sooo i think now there should be all properly added

shouldn't add stuff by hand when i already am half asleep ^^'

2023-05-21 12:01 UTC, Helias commented
@r-o-b-o-t-o what do you think?

2023-05-21 12:05 UTC, r-o-b-o-t-o approved these changes
Looks good, thanks!

2023-05-21 12:05 UTC, merged

2023-05-31 17:21 UTC, r-o-b-o-t-o commented
Just noticed this now while looking into https://github.com/azerothcore/mod-eluna/issues/144, you're using hooks that don't exist for your aura events...
I didn't notice the missing `override`s in `ElunaLuaEngine_SC.cpp` when reviewing.
Since the real aura hooks are in `UnitScript` and not `PlayerScript` I'm afraid I will have to revert this part of the PR, since we don't have Unit hooks.