Feature: Add Creature:GetCreatureByEntry(entry) as well as Global GetCreatureById(entry)
azerothcore/mod-eluna pull request #143
Opened 2023-05-29 04:06 UTC by New-HavenWotLK

2023-05-29 05:09 UTC, New-HavenWotLK commented
@Helias / @r-o-b-o-t-o: got one more... i am on fire! =D

2023-05-29 07:33 UTC, 55Honey commented
Thanks for the PR. I'm not sure if the naming of the new methods is consistent with the core. Interested to hear what others think.

2023-05-29 13:22 UTC, Helias commented
> Thanks for the PR. I'm not sure if the naming of the new methods is consistent with the core. Interested to hear what others think.

Are you referring to `GetCreatureById(entry)`? we could call it `GetCreatureTemplate` to be more coherent with the core, what do you think?

2023-05-29 13:50 UTC, New-HavenWotLK commented
> > Thanks for the PR. I'm not sure if the naming of the new methods is consistent with the core. Interested to hear what others think.
> 
> Are you referring to `GetCreatureById(entry)`? we could call it `GetCreatureTemplate` to be more coherent with the core, what do you think?

can change the global method according to that =)
would have no problem with it ^^

2023-05-29 14:28 UTC, New-HavenWotLK commented
sooo... changed now the global method to GetCreatureTemplate(entry) =)

2023-05-30 22:55 UTC, r-o-b-o-t-o commented on src/LuaEngine/CreatureMethods.h
> +    */
```suggestion

    /**
     * Retreives the entry ID of the [Creature].
     *
     * @param uint32 entry : the Creature ID to find.
     */
```

2023-05-30 22:56 UTC, r-o-b-o-t-o requested changes

2023-05-30 22:56 UTC, r-o-b-o-t-o commented on src/LuaEngine/GlobalMethods.h
> +    */
```suggestion

    /**
     * Retreives the entry ID of the [Creature]
     *
     * @param uint32 entry : the Creature ID to find
     */
```

2023-05-30 22:56 UTC, r-o-b-o-t-o commented on src/LuaEngine/LuaFunctions.cpp
> +
```suggestion
    { "GetCreatureTemplate", &LuaGlobalFunctions::GetCreatureTemplate },

```

2023-05-30 23:31 UTC, r-o-b-o-t-o commented
Reading this again, I'm not sure what you're trying to achieve with `GetCreatureByEntry`? You're returning a `CreatureTemplate` which is not even registered in Eluna 🤔

2023-05-31 01:07 UTC, New-HavenWotLK commented
> Reading this again, I'm not sure what you're trying to achieve with `GetCreatureByEntry`? You're returning a `CreatureTemplate` which is not even registered in Eluna 🤔

wanted in the end a creature method to gain directly a creature with a specifc entry so it doesn't need a for loop iteration inside a function to get a specific creature via creaturesInRange(range, entry)
The global one i made in the end so we can make an array of npc's and iterate then over this array on e.g. creaturedeath for all those creatures without the need of extra writing for every single creature a RegisterCreatureEvent line ^^

would the creature method eventually be accomplishable with this changed version here:

int GetCreatureByEntry(lua_State* L, Creature* creature)
    {
        uint32 entry = creature->GetEntry();
        CreatureTemplate const* cEntry = sObjectMgr->GetCreatureTemplate(entry);
        if (cEntry)
            Eluna::Push(L, cEntry->Entry);
        
        return 1;
    }

2023-05-31 16:01 UTC, hahalmtdhl commented
Can you tell me your ultimate goal?  :)

2023-05-31 16:18 UTC, New-HavenWotLK commented
> Can you tell me your ultimate goal? :)

the goal behind this is to get specific creatures at the same bossroom and to activate them after a specific time...

means... they already are spawned in but are kinda "deactivated" i want then in the end that boss gains the creature with entry xyz after e.g. 60 secs and activates them... but without the need of a for loop where it retreives the creatures out of a table from GetCreaturesInRange(range, entry)

so kinda like:

```
local check = creature:GetCreatureByEntry(NPC_EXAMPLE)
local checkFlags = check:GetUnitFlags()

if checkFlags == creatureFlags then
    check:SetUnitFlags(0)
    WaveOneOnCombat(event, creature, target)
end
```

2023-05-31 16:37 UTC, New-HavenWotLK commented
anyways...

it might not be my best idea... ROFL... was kinda stoned when i had this idea... ahahaha

so just let me know if u should scrap the creature method since the global method  would also be more than enough ^^

since then it still is checkable via the global one and IsInRange(target, range)

2023-06-02 16:46 UTC, GoMateoGo commented
According to your code, you should have already obtained creaturePtr

So there's no need to obtain creation through Entry again. Relying solely on Entry is not enough Entry is just an Index

All operations on Creature are performed through class pointers, not Creature ->entry



My guess:

You want to rewrite some boss AI within a replica

Are you currently obtaining CreaturePtr through GetCreaturesInRange?

But based on the code you displayed, you have already obtained it

2023-06-02 17:37 UTC, r-o-b-o-t-o commented
> so just let me know if u want me to scrap the creature method since the global method would also be more than enough in the end ^^

Yes please

2023-06-02 17:49 UTC, closed without merging