fix(core/func): GetSpeedRate + SetSpeedRate + ifdefs
azerothcore/mod-eluna pull request #155
Opened 2023-09-29 15:52 UTC by svenbledt

Fixxed: SetSpeed and GetSpeed Function
Added: SetSpeedRate and GetSpeedRate
Removed: Unnecessary Ifdef's

Foe recognized on the azerothcore mod-eluna repo that the SetSpeed function is using the wrong SetSpeedRate member of unit.

This PR changes that and seperates the functions from each other.

Also we decided to remove the ifdefs that are not needed as the module is only for azerothcore and not for Trinty or Mangos.

You can test this PR by using the functions in a script and check the impact ;) 

Thanks for your time!

2023-10-03 19:00 UTC, 55Honey commented
Thanks for the PR!

2023-10-03 19:13 UTC, r-o-b-o-t-o commented
Thanks for your PR!
It would have been nice if the `ifdefs` were removed in a separate PR, it would have improved readability and traceability 😛

It looks like you're not using `forced` in `SetSpeedRate`? If that was a leftover from copy-pasting the other function, please remove the variable.

2023-10-11 19:18 UTC, 55Honey commented
@svenbledt build is failing. Want to adjust?

2023-10-12 22:51 UTC, svenbledt commented
> @svenbledt build is failing. Want to adjust?

i sadly dont know why build is failing :D worked fine on my end :o

2023-10-14 11:02 UTC, r-o-b-o-t-o requested changes
The CI should work again now.
Sorry I forgot to mention this earlier, could you please add a change to the README file to document your additions? See an [example here](https://github.com/azerothcore/mod-eluna/commit/7c6e6dbbd0f1ed8d723bede90d42970fbdb4725d)

2023-10-14 11:02 UTC, r-o-b-o-t-o commented on src/LuaEngine/UnitMethods.h
> +            return luaL_argerror(L, 2, "valid UnitMoveType expected");
```suggestion
        if (type >= MAX_MOVE_TYPE)
        {
            return luaL_argerror(L, 2, "valid UnitMoveType expected");
        }
```

2023-10-14 11:02 UTC, r-o-b-o-t-o commented on src/LuaEngine/UnitMethods.h
> +            return luaL_argerror(L, 2, "valid UnitMoveType expected");
```suggestion
        if (type >= MAX_MOVE_TYPE)
        {
            return luaL_argerror(L, 2, "valid UnitMoveType expected");
        }
```

2023-10-14 11:02 UTC, r-o-b-o-t-o commented on src/LuaEngine/UnitMethods.h
>              return luaL_argerror(L, 2, "valid UnitMoveType expected");
```suggestion
        if (type >= MAX_MOVE_TYPE)
        {
            return luaL_argerror(L, 2, "valid UnitMoveType expected");
        }
```

2023-10-14 11:02 UTC, r-o-b-o-t-o commented on src/LuaEngine/UnitMethods.h
>              return luaL_argerror(L, 2, "valid UnitMoveType expected");
```suggestion
        if (type >= MAX_MOVE_TYPE)
        {
            return luaL_argerror(L, 2, "valid UnitMoveType expected");
        }
```

2023-10-14 12:17 UTC, svenbledt reviewed
Thanks mate

2023-10-14 15:46 UTC, r-o-b-o-t-o commented on README.md
> +- Added `Unit:SetSpeedRate(UnitMoveType, speed)`: https://github.com/azerothcore/mod-eluna/pull/155
```suggestion
- Added `Unit:SetSpeedRate(unitMoveType, speed)`: https://github.com/azerothcore/mod-eluna/pull/155
```

2023-10-14 15:47 UTC, merged